#!/usr/bin/env node
// Regenerate assets/fonts/material-symbols-outlined.woff2 — Google's own
// subset of Material Symbols Outlined holding every glyph the comps and the
// app use. A glyph missing from the subset renders as its NAME in letters
// ("settings" measured 152×23 against the comp's 19×23 on 2026-08-29), so run
// this whenever a comp or the app gains an icon:
//
//   node packages/annotator/scripts/icon-subset.mjs [--check]
//
// The list is derived, never typed: every quoted token in design/refdiff/**
// (the comps put a third of their icons in script arrays) and in
// packages/annotator/src/*.ts, intersected with Google's codepoints list, plus
// the static `class="msi"` markup. It writes the face AND the generated
// `src/icon-names.ts` (the list the font URL's version hashes, so a browser
// never serves a stale subset). --check prints the list and exits 1 if it
// differs from the committed one. Needs the
// network (the codepoints list from GitHub, the face from fonts.gstatic.com).
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, "..", "..", "..")
const fontsDir = join(here, "..", "assets", "fonts")
const CODEPOINTS =
  "https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints"
const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"

const walk = (dir, pred) =>
  readdirSync(dir).flatMap((name) => {
    const p = join(dir, name)
    if (name === "node_modules" || name === "dist") return []
    return statSync(p).isDirectory() ? walk(p, pred) : pred(p) ? [p] : []
  })

const sources = [
  ...walk(join(root, "design", "refdiff"), (p) => p.endsWith(".dc.html")),
  ...walk(join(root, "packages", "annotator", "src"), (p) => p.endsWith(".ts") && !p.endsWith(".test.ts")),
]

const known = new Set(
  (await (await fetch(CODEPOINTS)).text())
    .split("\n")
    .map((l) => l.trim().split(/\s+/)[0])
    .filter(Boolean),
)
const used = new Set()
for (const file of sources) {
  const s = readFileSync(file, "utf8")
  for (const m of s.matchAll(/class="msi[^"]*"[^>]*>([a-z_0-9]+)</g)) used.add(m[1])
  for (const m of s.matchAll(/['"]([a-z][a-z_0-9]{2,})['"]/g)) if (known.has(m[1])) used.add(m[1])
}
const names = [...used].sort()
const listFile = join(here, "..", "src", "icon-names.ts")
const listSource = (list) =>
  "// GENERATED by scripts/icon-subset.mjs — do not edit. Every Material Symbols glyph the comps\n" +
  "// and the app use; the icon face under assets/fonts/ is Google's subset of exactly these, and\n" +
  "// fonts.ts hashes this list into the font URL so a re-subsetted face is never served stale.\n" +
  "export const ICON_NAMES: readonly string[] = [\n" +
  list.map((n) => `  "${n}",`).join("\n") +
  "\n]\n"
const committed = (() => {
  try {
    return readFileSync(listFile, "utf8")
  } catch {
    return ""
  }
})()
if (process.argv.includes("--check")) {
  console.log(names.join(","))
  if (committed !== listSource(names)) {
    console.error(`icon subset out of date: ${names.length} glyphs used — run without --check`)
    process.exit(1)
  }
  process.exit(0)
}

const css = await (
  await fetch(
    `https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,300..600,0..1,-50..200&icon_names=${names.join(",")}&display=block`,
    { headers: { "user-agent": UA } },
  )
).text()
const url = /url\((https:[^)]+)\)/.exec(css)?.[1]
if (!url) throw new Error(`no woff2 url in Google's CSS:\n${css}`)
const woff2 = Buffer.from(await (await fetch(url)).arrayBuffer())
writeFileSync(join(fontsDir, "material-symbols-outlined.woff2"), woff2)
writeFileSync(listFile, listSource(names))
console.log(`${names.length} glyphs, ${woff2.length} bytes → assets/fonts/material-symbols-outlined.woff2 + src/icon-names.ts`)
