#!/usr/bin/env bash
# refdiff — dev-mode setup for a new machine / VM. Idempotent; re-run any time.
#
#   bash ~/.claude-shared/skills/refdiff/setup-dev.sh [--checkout <dir>] [--watch] [--no-browser]
#
# What it makes true:
#   1. a refdiff checkout exists (default ~/Development/refdiff; cloned if missing)
#   2. deps installed, Playwright Chromium present, both packages built
#   3. `refdiff` and `refdiff-annotator` on PATH as wrapper scripts (they exec dist/cli.js)
#   4. the skill is USER-level: ~/.claude/skills/refdiff (and ~/.claude-personal if present) →
#      <checkout>/skills/refdiff, via ~/.claude-shared/skills when that dir already exists
#   5. --watch: `pnpm dev` (tsc --watch, both packages) running in the background so dist follows edits
# Nothing is written into consuming repos; they only carry a manifest + refdiff.bindings.md.
set -euo pipefail

REPO_URL="https://github.com/mzvonar/refdiff.git"
CHECKOUT="${REFDIFF_DIR:-$HOME/Development/refdiff}"
WATCH=0
BROWSER=1
while [ $# -gt 0 ]; do
  case "$1" in
    --checkout) CHECKOUT="$2"; shift 2 ;;
    --watch) WATCH=1; shift ;;
    --no-browser) BROWSER=0; shift ;;
    -h|--help) sed -n '2,15p' "$0"; exit 0 ;;
    *) echo "unknown option $1" >&2; exit 2 ;;
  esac
done

say() { printf '\033[1m%s\033[0m\n' "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || { echo "missing: $1 ($2)" >&2; exit 1; }; }

need node "Node ≥22"
need pnpm "corepack enable && corepack prepare pnpm@10 --activate"
need git "git"
NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]')
[ "$NODE_MAJOR" -ge 22 ] || { echo "Node ≥22 required, have $(node -v)" >&2; exit 1; }

# 1. checkout
if [ -d "$CHECKOUT/.git" ]; then
  say "checkout: $CHECKOUT ($(git -C "$CHECKOUT" rev-parse --short HEAD), $(git -C "$CHECKOUT" branch --show-current))"
else
  say "cloning $REPO_URL → $CHECKOUT"
  mkdir -p "$(dirname "$CHECKOUT")"
  git clone --quiet "$REPO_URL" "$CHECKOUT"
fi
cd "$CHECKOUT"

# 2. deps, browser, build
say "pnpm install"
pnpm install --frozen-lockfile --reporter=silent 2>/dev/null || pnpm install --reporter=silent
if [ "$BROWSER" = 1 ]; then
  say "playwright chromium"
  ( cd packages/core && pnpm exec playwright install chromium >/dev/null )
fi
say "pnpm build"
pnpm build >/dev/null

# 3. global bins. `pnpm link --global` did this until pnpm 10.33 REMOVED the no-argument
#    self-link form: `pnpm link` now demands a <dir|pkg name> and fails with
#    ERR_PNPM_LINK_BAD_PARAMS without one. `pnpm add -g <dir>` is NOT a substitute —
#    @refdiff/annotator depends on `@refdiff/core: workspace:*`, which does not resolve
#    outside the workspace. Two further pnpm behaviours used to bite here:
#      - `pnpm setup` only appends the PATH line to the shell PROFILE; it does not change
#        THIS shell, so anything later in this script still runs without it.
#      - `pnpm bin -g` refuses to report the dir unless it is already on PATH, and the two
#        pnpm generations disagree about which dir that is: 10.x reports $PNPM_HOME, while
#        `pnpm setup` puts $PNPM_HOME/bin on PATH. Querying it IS the chicken-and-egg.
#    So: stop asking pnpm, and install our own wrappers into a dir that is on PATH.
#    WRAPPERS, not symlinks — tsc emits dist/cli.js with mode 0644, so a symlink to it is
#    not executable after any clean rebuild (pnpm's own shims existed for this reason).
on_path() { case ":$PATH:" in *":$1:"*) return 0 ;; *) return 1 ;; esac; }
usable_dir() { { [ -d "$1" ] || mkdir -p "$1" 2>/dev/null; } && [ -w "$1" ]; }
bin_candidates() {
  # Newline-delimited, never word-split: $HOME may contain spaces (macOS).
  [ -n "${PNPM_HOME:-}" ] && { printf '%s\n' "$PNPM_HOME/bin" "$PNPM_HOME"; }
  printf '%s\n' "$HOME/.local/bin" "$HOME/bin"
}

BIN_DIR=""
while IFS= read -r d; do                      # first choice: a dir already on PATH
  [ -n "$d" ] || continue
  if on_path "$d" && usable_dir "$d"; then BIN_DIR="$d"; break; fi
done <<EOF
$(bin_candidates)
EOF
if [ -z "$BIN_DIR" ]; then                    # else: the first we can create, and say so
  while IFS= read -r d; do
    [ -n "$d" ] || continue
    if usable_dir "$d"; then BIN_DIR="$d"; break; fi
  done <<EOF
$(bin_candidates)
EOF
fi

# A bin failure must not cost the skill symlinks (step 4) — they are independent.
if [ -z "$BIN_DIR" ]; then
  echo "warn: no writable bin dir found — the CLIs are not on PATH. Run them from the" >&2
  echo "      checkout instead: node $CHECKOUT/packages/core/dist/cli.js" >&2
else
  say "cli wrappers -> $BIN_DIR"
  for pair in refdiff:core refdiff-annotator:annotator; do
    cmd="${pair%%:*}"; pkg="${pair##*:}"
    printf '%s\n' \
      '#!/usr/bin/env bash' \
      '# Generated by refdiff skills/refdiff/setup-dev.sh — re-run it to refresh.' \
      '# A wrapper, not a symlink: tsc emits dist/cli.js mode 0644, so a symlink to it' \
      '# stops being executable after a clean rebuild.' \
      "exec node \"$CHECKOUT/packages/$pkg/dist/cli.js\" \"\$@\"" \
      > "$BIN_DIR/$cmd"
    chmod +x "$BIN_DIR/$cmd"
  done
  on_path "$BIN_DIR" || \
    echo "note: $BIN_DIR is not on PATH in your profile — add it:  export PATH=\"$BIN_DIR:\$PATH\""
fi

# 4. user-level skill symlinks. With the two-profile setup (~/.claude-shared exists) follow its
#    convention: shared → checkout, profiles → shared. On a plain machine (only ~/.claude) link the
#    profile straight to the checkout — never create ~/.claude-shared where it is not in use.
SKILL_SRC="$CHECKOUT/skills/refdiff"
LINK_TARGET="$SKILL_SRC"
if [ -d "$HOME/.claude-shared" ]; then
  mkdir -p "$HOME/.claude-shared/skills"
  ln -sfn "$SKILL_SRC" "$HOME/.claude-shared/skills/refdiff"
  LINK_TARGET="$HOME/.claude-shared/skills/refdiff"
fi
linked=0
for profile in "$HOME/.claude" "$HOME/.claude-personal"; do
  [ -d "$profile" ] || continue
  mkdir -p "$profile/skills"
  if [ -e "$profile/skills/refdiff" ] && [ ! -L "$profile/skills/refdiff" ]; then
    echo "note: $profile/skills/refdiff is a real directory, not replacing it (remove it to link the checkout)"
    continue
  fi
  ln -sfn "$LINK_TARGET" "$profile/skills/refdiff"
  say "skill: $profile/skills/refdiff → $LINK_TARGET"
  linked=1
done
if [ "$linked" = 0 ]; then
  mkdir -p "$HOME/.claude/skills"
  ln -sfn "$LINK_TARGET" "$HOME/.claude/skills/refdiff"
  say "skill: ~/.claude/skills/refdiff → $LINK_TARGET (no profile dir existed; created ~/.claude/skills)"
fi

# 5. watcher
if [ "$WATCH" = 1 ]; then
  if pgrep -f "tsc -p tsconfig(.build)?.json --watch" >/dev/null 2>&1; then
    say "watcher already running (pnpm dev)"
  else
    say "starting pnpm dev (tsc --watch) in the background → $CHECKOUT/.dev.log"
    nohup pnpm dev >"$CHECKOUT/.dev.log" 2>&1 &
    disown || true
  fi
fi

# verify
say "verify"
if [ -n "${BIN_DIR:-}" ] && [ -x "$BIN_DIR/refdiff" ]; then
  "$BIN_DIR/refdiff" --help | head -1
else
  node packages/core/dist/cli.js --help | head -1
fi
echo "tests: $(pnpm -r test 2>&1 | grep -oE 'Tests +[0-9]+ passed' | awk '{s+=$2} END {print s+0}') passing"
# The pre-flight is the same check a session runs before its first compare, so running it here
# proves the install is COHERENT rather than merely complete — a build that landed but did not
# finish, or a checkout behind origin, shows up now instead of as a +0/-0 delta later.
echo
bash "$CHECKOUT/skills/refdiff/preflight.sh" || true
echo
echo "dev mode ready. Edit $SKILL_SRC/SKILL.md or packages/*/src — the skill is live, dist follows with pnpm dev."
echo "A consuming repo needs only: its manifest + a refdiff.bindings.md (see SKILL.md 'Repo bindings')."
